### ISSUE TITLE
Cannot find the q3_weights.pickle

### ISSUE THREAD

**Issue by roec** [ziliHarvey/Optical-Character-Recognition#1]
Hi Z, I looked around your directory, there isn't q3_weights.pickle file which written in textExtraction.py, line of 48.

**Comment by ziliHarvey** [comment]
Hi Roec,
Thanks for contacting me. q3_weights.pickle saves the parameters I trained on NIST36 dataset so that I can just load them instead of training the network again. Please refer to realDataTest.py line 106, and you will get q3_weights.pickle after running realDataTest.py.
Hope it helps :)

**Comment by roec** [comment]
Great! Zili
If you have spare time, could we discuss some real cases, actually in my hands  I have a lot of them.

**Comment by ziliHarvey** [comment]
For real cases like word extraction, I believe those state-of-the-art deep learning algorithm like YOLO is much more practical, my code is a basic implementation for understanding how it works behind the scene. And yea, feel free to email me at zili@andrew.cmu.edu and let's see what we can do.
